name: Naukri Auto Update

on:
  schedule:
    # Daily Subah 8:30 AM IST (3:00 AM UTC)
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Script
        env:
          NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
        run: python main.py
